[theme]
base = "dark"
primaryColor = "#00E7FF"
backgroundColor = "#07101D"
secondaryBackgroundColor = "#0D192A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
